---
name: "Docker Build"
description: "Build Docker image with caching"

inputs:
  context:
    description: "Context directory for Docker build"
    required: false
    default: "."
  cache-key:
    description: "Cache key for this image"
    required: false
    default: "default"
  dockerfile:
    description: "Path to Dockerfile"
    required: false
    default: './Dockerfile'
  image:
    description: "Docker image name"
    required: false
    default: "app:latest"
  labels:
    description: "List of metadata for an image"
    required: false
  load:
    description: "Load is a shorthand for --output=type=docker"
    required: false
    default: "true"
  push:
    description: "Push is a shorthand for --output=type=registry"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    -
      name: Set up Cache for Docker build
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache-${{ inputs.image }}
        key: ${{ runner.os }}-buildx-${{ inputs.cache-key }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ inputs.cache-key }}-
          ${{ runner.os }}-buildx-
    -
      name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        pull: true
        push: ${{ inputs.push }}
        load: ${{ inputs.load }}
        tags: ${{ inputs.image }}
        labels: ${{ inputs.labels }}
        cache-from: type=local,src=/tmp/.buildx-cache-${{ inputs.image }}
        cache-to: type=local,dest=/tmp/.buildx-cache-${{ inputs.image }}-new,mode=max
    -
      name: Archive Docker build cache results
      # Docker image layer solution origin:
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      shell: sh
      run: |
        echo "Archive Docker build cache results..."
        [ -f "/tmp/.buildx-cache-${{ inputs.image }}" ] && \
          du --human-readable --summarize -- "/tmp/.buildx-cache-${{ inputs.image }}"
        du --human-readable --summarize -- "/tmp/.buildx-cache-${{ inputs.image }}-new"
        rm -rf -- "/tmp/.buildx-cache-${{ inputs.image }}"
        mv -- "/tmp/.buildx-cache-${{ inputs.image }}-new" "/tmp/.buildx-cache-${{ inputs.image }}"
        echo "Moving Docker build cache finished"
