---
name: "Docker Build"
description: "Build Docker image with caching"

inputs:
  context:
    description: "Context directory for Docker build"
    required: false
    default: "."
  cache-key:
    description: "Cache key for this image"
    required: false
    default: "default"
  dockerfile:
    description: "Path to Dockerfile"
    required: false
    default: './Dockerfile'
  tags:
    description: "Docker image tag list"
    required: true
    default: "app:latest"
  labels:
    description: "List of metadata for a Docker image"
    required: false
  load:
    description: "Load is a shorthand for --output=type=docker"
    required: false
    default: "true"
  push:
    description: "Push is a shorthand for --output=type=registry"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    -
      name: Extract first Docker image tag from tag list
      id: extract_first_tag
      shell: bash
      run: |
        tags="${{ inputs.tags }}"
        echo "tags: [[$tags]]"
        first_tag="$(echo "$tags" | head --lines=1)"
        echo "first_tag: [[$first_tag]]"
        echo "::set-output name=value::$first_tag"
    -
      name: Calculate docker cache directory
      id: get_cache_dir
      shell: bash
      run: |
        echo "::set-output name=value::/tmp/.buildx-cache-${{ steps.extract_first_tag.outputs.value }}"
    -
      name: Set up Cache for Docker build
      uses: actions/cache@v2
      with:
        path: ${{ steps.get_cache_dir.outputs.value }}
        key: ${{ runner.os }}-buildx-${{ inputs.cache-key }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ inputs.cache-key }}-
          ${{ runner.os }}-buildx-
    -
      name: Build Docker image
      uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        pull: true
        push: ${{ inputs.push }}
        load: ${{ inputs.load }}
        tags: ${{ inputs.tags }}
        labels: ${{ inputs.labels }}
        cache-from: type=local,src=${{ steps.get_cache_dir.outputs.value }}
        cache-to: type=local,dest=${{ steps.get_cache_dir.outputs.value }}-new,mode=max
    -
      name: Archive Docker build cache results
      # Docker image layer solution origin:
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      shell: sh
      run: |
        echo "Archive Docker build cache results..."
        [ -f "/tmp/.buildx-cache-$first_tag" ] && \
          du --human-readable --summarize -- "${{ steps.get_cache_dir.outputs.value }}"
        du --human-readable --summarize -- "${{ steps.get_cache_dir.outputs.value }}-new"
        rm -rf -- "${{ steps.get_cache_dir.outputs.value }}"
        mv -- "${{ steps.get_cache_dir.outputs.value }}-new" "${{ steps.get_cache_dir.outputs.value }}"
        echo "Moving Docker build cache finished"
