---
default: true

# Trailing spaces
MD009:
  br_spaces: 2

# Line length
MD013:
  line_length: 100
  code_blocks: false
  tables: false

# Multiple headers with same content
MD024:
  siblings_only: true
