---
name: "Limbo: Python (raw)"

"on":
  push:
    branches: [master, dev, release/**]
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:

  check-code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Markdown syntax
        run: |
          make -- check-md
      - name: Check YAML syntax
        run: |
          make -- check-yaml
      - name: Check Makefile syntax
        run: |
          make -- check-make
      - name: Check Python syntax (PEP8)
        run: |
          make -- check-pep8

  run-code-analyze:
    strategy:
      matrix:
        python_version: ["3.7", "3.8"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python_version }}
          cache: pip
          cache-dependency-path: |
            requirements.txt
            requirements.dev.txt
      - name: Install dependencies (pip)
        run: |
          python -m pip install --upgrade -- pip
          pip install \
            --requirement=requirements.txt \
            --requirement=requirements.dev.txt
      - name: Run mypy
        run: |
          make -- check-mypy
      - name: Run pylint
        run: |
          make -- check-lint-local

  run-unit-tests:
    strategy:
      matrix:
        python_version: ["3.7", "3.8"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python_version }}
          cache: pip
          cache-dependency-path: |
            requirements.txt
            requirements.dev.txt
      - name: Install dependencies (pip)
        run: |
          python -m pip install --upgrade -- pip
          pip install \
            --requirement=requirements.txt \
            --requirement=requirements.dev.txt
      - name: Run unit tests (pytest)
        run: |
          make -- test
